version: '3.5'

services:
  source-db-enterprise-com:
    image: ${DOCKER_REGISTRY}source-db.enterprise.com:${BRANCH:-develop}.${VERSION:-local}-tests
    container_name: software-db-tests.enterprise.com
    build:
      target: tests
    environment:
      # RUN_TEST: ${RUN_TEST:-true}
      # RUN_PROJECT: ${RUN_PROJECT:-false}
      RUN_SONARQUBE: ${RUN_SONARQUBE:-true}
      SONARQUBE_URL: ${SONARQUBE_URL:-http://172.17.0.1:9000}
      SONARQUBE_LOGIN: ${SONARQUBE_LOGIN}
      SONARQUBE_PROJECT: source-db.enterprise.com
      SONARQUBE_PROJECT_VERSION: ${VERSION:-local}
      DATABASE: Banco
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
      MSSQL_AGENT_ENABLED: 'true'
    volumes:
      - test-result:/TestResults

volumes:
  test-result:
    name: ${DOCKERCOMPOSE_CI_VOLUME_NAME:-app-test-results}

networks:
  default:
    name: ns-software-db-${BRANCH}-${VERSION}-tests    
