version: '3.5'

services:
  source-db-enterprise-com:
    image: ${DOCKER_REGISTRY}source-db.enterprise.com:${BRANCH}.${VERSION}
    environment:
      DATABASE: Banco
      SA_PASSWORD: P@ssw0rd
      MSSQL_AGENT_ENABLED: 'true'
      ACCEPT_EULA: 'Y'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "\"SELECT 1\"", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    labels:
      kompose.service.expose: source-db.enterprise.com

networks:
  default:
    name: ns-software-beta
